GIGO.sites_parsed={
 "8n1.org": {
  "mirror": "0",
  "site": "8n1.org",
  "hide": "0",
  "v4": "http://ip4.8n1.org/test.gif",
  "v6": "http://ip6.8n1.org/test.gif",
  "loc": "NL",
  "provider": "8n1.org - a simple pastebin",
  "monitor": "Sander Smeenk \u003csander@bit.nl\u003e",
  "reason": ""
 },
 "aa.net.uk": {
  "mirror": "0",
  "site": "aa.net.uk",
  "hide": "0",
  "v4": "http://ip4.aa.net.uk/images/aaisp_logo.png",
  "v6": "http://ip6.aa.net.uk/images/aaisp_logo.png",
  "loc": "UK",
  "provider": "AAISP (UK IPv6 ISP)",
  "monitor": "Adrian Kennard \u003ca@k.gg\u003e",
  "reason": ""
 },
 "campaya.co.uk": {
  "mirror": "0",
  "site": "campaya.co.uk",
  "hide": "0",
  "v4": "http://ipv4.campaya.co.uk/apple-touch-icon.png",
  "v6": "http://ipv6.campaya.co.uk/apple-touch-icon.png",
  "loc": "UK",
  "provider": "Campaya",
  "monitor": "Claus Pedersen \u003cclausp@campaya.com\u003e",
  "reason": ""
 },
 "chelloo.com": {
  "mirror": "0",
  "site": "chelloo.com",
  "hide": "0",
  "v4": "http://ipv4.chelloo.com/images/pixel.gif",
  "v6": "http://ipv6.chelloo.com/images/pixel.gif",
  "loc": "NL",
  "provider": "Chelloo",
  "monitor": "Rene Kemp \u003crene.kemp@outlook.com\u003e",
  "reason": ""
 },
 "duplimaster.com": {
  "mirror": "0",
  "site": "duplimaster.com",
  "hide": "0",
  "v4": "http://ipv4.duplimaster.com/public/images/logo-sombra.png",
  "v6": "http://ipv6.duplimaster.com/public/images/logo-sombra.png",
  "loc": "ES",
  "provider": "duplimaster.com",
  "monitor": "Jesus Vara \u003cjvara@e-impresion.es\u003e",
  "reason": ""
 },
 "eurobilltracker.com": {
  "mirror": "0",
  "site": "eurobilltracker.com",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.eurobilltracker.com/img/1x1.gif",
  "v6": "http://ipv6.test-ipv6.eurobilltracker.com/img/1x1.gif",
  "loc": "FI",
  "provider": "EuroBillTracker",
  "monitor": "Anssi Johansson \u003canssi@miuku.net\u003e",
  "reason": ""
 },
 "google.com": {
  "mirror": "0",
  "site": "google.com",
  "hide": "0",
  "v4": "http://test-ipv6-dot-com-v6exp3-v4.metric.gstatic.com/v6exp3/6.gif",
  "v6": "http://test-ipv6-dot-com-v6exp3-v6.metric.gstatic.com/v6exp3/6.gif",
  "loc": "global",
  "provider": "Google",
  "monitor": "",
  "reason": ""
 },
 "he.net": {
  "mirror": "0",
  "site": "he.net",
  "hide": "0",
  "v4": "http://ipv4.tunnelbroker.net/images/helogo.gif",
  "v6": "http://ipv6.tunnelbroker.net/images/helogo.gif",
  "loc": "US (CA)",
  "provider": "HE.net",
  "monitor": "Mike Tindle \u003cmtindle@he.net\u003e",
  "reason": ""
 },
 "ipv6-test.pl": {
  "mirror": "1",
  "site": "ipv6-test.pl",
  "hide": "0",
  "v4": "http://ipv4.ipv6-test.pl/images-nc/knob_green.png",
  "v6": "http://ipv6.ipv6-test.pl/images-nc/knob_green.png",
  "loc": "PL",
  "provider": "Net-Admin",
  "monitor": "",
  "reason": ""
 },
 "nic.br": {
  "mirror": "0",
  "site": "nic.br",
  "hide": "0",
  "v4": "http://v4.ipv6.br/img/logo-ipv6.png",
  "v6": "http://v6.ipv6.br/img/logo-ipv6.png",
  "loc": "BR",
  "provider": "NIC.br",
  "monitor": "Antonio M. Moreiras \u003cmoreiras@nic.br\u003e",
  "reason": ""
 },
 "nsx.de": {
  "mirror": "0",
  "site": "nsx.de",
  "hide": "0",
  "v4": "http://ipv4.nsx.de/images/knob_valid_green.png",
  "v6": "http://ipv6.nsx.de/images/knob_valid_green.png",
  "loc": "DE",
  "provider": "Stephan Fiebrandt (personal)",
  "monitor": "Stephan Fiebrandt \u003cstephan@nsx.de\u003e",
  "reason": ""
 },
 "sixte.st": {
  "mirror": "1",
  "site": "sixte.st",
  "hide": "0",
  "v4": "http://ipv4.sixte.st/images-nc/knob_green.png",
  "v6": "http://ipv6.sixte.st/images-nc/knob_green.png",
  "loc": "SG",
  "provider": "Delan Azabani",
  "monitor": "Delan Azabani \u003cdelan@azabani.com\u003e",
  "reason": ""
 },
 "snozzages.com": {
  "mirror": "0",
  "site": "snozzages.com",
  "hide": "0",
  "v4": "http://ipv4.v6test.snozzages.com/1x1.gif",
  "v6": "http://ipv6.v6test.snozzages.com/1x1.gif",
  "loc": "US (VA)",
  "provider": "Warren Kumari",
  "monitor": "Warren Kumari \u003cwarren@kumari.net\u003e",
  "reason": ""
 },
 "stdio.be": {
  "mirror": "0",
  "site": "stdio.be",
  "hide": "0",
  "v4": "http://ipv4.stdio.be/images/knob_valid_green.png",
  "v6": "http://ipv6.stdio.be/images/knob_valid_green.png",
  "loc": "DE",
  "provider": "Andrew Yourtchenko (personal)",
  "monitor": "",
  "reason": ""
 },
 "test-ipv6-ct.comcast.net": {
  "mirror": "1",
  "site": "test-ipv6-ct.comcast.net",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6-ct.comcast.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6-ct.comcast.net/images-nc/knob_green.png",
  "loc": "US",
  "provider": "Comcast",
  "monitor": "Comcast IPv6 Team \u003ccomcast-ipv6@cable.comcast.com\u003e",
  "reason": ""
 },
 "test-ipv6-pa.comcast.net": {
  "mirror": "1",
  "site": "test-ipv6-pa.comcast.net",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6-pa.comcast.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6-pa.comcast.net/images-nc/knob_green.png",
  "loc": "US",
  "provider": "Comcast",
  "monitor": "Comcast IPv6 Team \u003ccomcast-ipv6@cable.comcast.com\u003e",
  "reason": ""
 },
 "test-ipv6.alpinedc.ch": {
  "mirror": "1",
  "site": "test-ipv6.alpinedc.ch",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.alpinedc.ch/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.alpinedc.ch/images-nc/knob_green.png",
  "loc": "CH",
  "provider": "AlpineDC",
  "monitor": "Sebastien Morier \u003csmorier@alpinedc.ch\u003e",
  "reason": ""
 },
 "test-ipv6.ams.vr.org": {
  "mirror": "1",
  "site": "test-ipv6.ams.vr.org",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.ams.vr.org/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.ams.vr.org/images-nc/knob_green.png",
  "loc": "NL",
  "provider": "vr.org",
  "monitor": "jfesler@gigo.com",
  "reason": ""
 },
 "test-ipv6.arbor.net": {
  "mirror": "1",
  "site": "test-ipv6.arbor.net",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.arbor.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.arbor.net/images-nc/knob_green.png",
  "loc": "US",
  "provider": "Arbor Networks",
  "monitor": "Bill Cerveny \u003cadmin@v6research.net\u003e",
  "reason": ""
 },
 "test-ipv6.azstarnet.az": {
  "mirror": "1",
  "site": "test-ipv6.azstarnet.az",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.azstarnet.az/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.azstarnet.az/images-nc/knob_green.png",
  "loc": "AZ",
  "provider": "AZSTARNET LLC",
  "monitor": "Nadir M. Aliyev \u003cnadir@azstarnet.az\u003e",
  "reason": ""
 },
 "test-ipv6.bakinter.net": {
  "mirror": "1",
  "site": "test-ipv6.bakinter.net",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.bakinter.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.bakinter.net/images-nc/knob_green.png",
  "loc": "AZ",
  "provider": "Baktelekom",
  "monitor": "Nadir M. Aliyev \u003cadmin@bakinter.net\u003e",
  "reason": ""
 },
 "test-ipv6.belwue.net": {
  "mirror": "1",
  "site": "test-ipv6.belwue.net",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.belwue.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.belwue.net/images-nc/knob_green.png",
  "loc": "DE",
  "provider": "BelWü",
  "monitor": "BelWue NOC \u003cip@belwue.de\u003e",
  "reason": ""
 },
 "test-ipv6.carnet.hr": {
  "mirror": "1",
  "site": "test-ipv6.carnet.hr",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.carnet.hr/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.carnet.hr/images-nc/knob_green.png",
  "loc": "HR",
  "provider": "Croatian Academic and Research Network",
  "monitor": "CARNet \u003csysadm@carnet.hr\u003e",
  "reason": ""
 },
 "test-ipv6.chi.vr.org": {
  "mirror": "1",
  "site": "test-ipv6.chi.vr.org",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.chi.vr.org/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.chi.vr.org/images-nc/knob_green.png",
  "loc": "US IL",
  "provider": "vr.org",
  "monitor": "jfesler@gigo.com",
  "reason": ""
 },
 "test-ipv6.co.za": {
  "mirror": "1",
  "site": "test-ipv6.co.za",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.co.za/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.co.za/images-nc/knob_green.png",
  "loc": "ZA",
  "provider": "Multisource Telecoms",
  "monitor": "Multisource Support \u003csupport@multisource.co.za\u003e",
  "reason": ""
 },
 "test-ipv6.com": {
  "mirror": "1",
  "site": "test-ipv6.com",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.com/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.com/images-nc/knob_green.png",
  "loc": "US CA",
  "provider": "Jason Fesler",
  "monitor": "",
  "reason": ""
 },
 "test-ipv6.com.au": {
  "mirror": "1",
  "site": "test-ipv6.com.au",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.com.au/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.com.au/images-nc/knob_green.png",
  "loc": "AU",
  "provider": "Futzle Industries",
  "monitor": "",
  "reason": ""
 },
 "test-ipv6.cz": {
  "mirror": "1",
  "site": "test-ipv6.cz",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.cz/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.cz/images-nc/knob_green.png",
  "loc": "CZ",
  "provider": "nic.cz",
  "monitor": "NOC NIC \u003cnoc@nic.cz\u003e",
  "reason": ""
 },
 "test-ipv6.ernet.in": {
  "mirror": "1",
  "site": "test-ipv6.ernet.in",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.ernet.in/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.ernet.in/images-nc/knob_green.png",
  "loc": "IN",
  "provider": "IPv6 Division of ERNET India",
  "monitor": "Praveen Misra \u003cpraveen@ipv6.ernet.in\u003e",
  "reason": ""
 },
 "test-ipv6.fratec.net": {
  "mirror": "1",
  "site": "test-ipv6.fratec.net",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.fratec.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.fratec.net/images-nc/knob_green.png",
  "loc": "CR",
  "provider": "Sistemas Fratec S.A.",
  "monitor": "",
  "reason": ""
 },
 "test-ipv6.go6.si": {
  "mirror": "1",
  "site": "test-ipv6.go6.si",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.go6.si/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.go6.si/images-nc/knob_green.png",
  "loc": "SI",
  "provider": "Go6 Lab - Slovenian IPv6 Iniciative",
  "monitor": "Jan Zorz \u003cjan@go6.si\u003e",
  "reason": ""
 },
 "test-ipv6.hu": {
  "mirror": "1",
  "site": "test-ipv6.hu",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.hu/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.hu/images-nc/knob_green.png",
  "loc": "HU",
  "provider": "Polaris-N Systems",
  "monitor": "Polaris-N Systems \u003cinfo@polaris-n.hu\u003e",
  "reason": ""
 },
 "test-ipv6.iad.vr.org": {
  "mirror": "1",
  "site": "test-ipv6.iad.vr.org",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.iad.vr.org/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.iad.vr.org/images-nc/knob_green.png",
  "loc": "US VA",
  "provider": "vr.org",
  "monitor": "jfesler@gigo.com",
  "reason": ""
 },
 "test-ipv6.jp": {
  "mirror": "1",
  "site": "test-ipv6.jp",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.jp/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.jp/images-nc/knob_green.png",
  "loc": "JP",
  "provider": "BIGLOBE, Inc/Fullroute Pte. Ltd",
  "monitor": "Shin Shirahata \u003cinquiry@test-ipv6.jp\u003e",
  "reason": ""
 },
 "test-ipv6.lazypaddle.com": {
  "mirror": "1",
  "site": "test-ipv6.lazypaddle.com",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.lazypaddle.com/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.lazypaddle.com/images-nc/knob_green.png",
  "loc": "US WI",
  "provider": "Dale Hartung",
  "monitor": "Dale Hartung \u003cdale@dghartung.com\u003e",
  "reason": ""
 },
 "test-ipv6.monash.edu": {
  "mirror": "1",
  "site": "test-ipv6.monash.edu",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.monash.edu/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.monash.edu/images-nc/knob_green.png",
  "loc": "AU",
  "provider": "Monash University",
  "monitor": "John Mann \u003cJohn.Mann@monash.edu\u003e",
  "reason": ""
 },
 "test-ipv6.netiter.dk": {
  "mirror": "0",
  "site": "test-ipv6.netiter.dk",
  "hide": "0",
  "v4": "http://test-ipv6.com.i42.test-ipv6.easyv6.net/ipv6-test.png",
  "v6": "http://test-ipv6.com.i32.test-ipv6.easyv6.net/ipv6-test.png",
  "loc": "DE",
  "provider": "Netiter ApS",
  "monitor": "Netiter Aps \u003ckontakt@netiter.dk\u003e",
  "reason": ""
 },
 "test-ipv6.nl": {
  "mirror": "1",
  "site": "test-ipv6.nl",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.nl/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.nl/images-nc/knob_green.png",
  "loc": "NL",
  "provider": "BIT BV",
  "monitor": "Teun Vink \u003cteun@bit.nl\u003e",
  "reason": ""
 },
 "test-ipv6.no": {
  "mirror": "1",
  "site": "test-ipv6.no",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.no/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.no/images-nc/knob_green.png",
  "loc": "NO",
  "provider": "Availo AS",
  "monitor": "Brynjar Eide \u003ctest-ipv6@availo.no\u003e",
  "reason": ""
 },
 "test-ipv6.polkam.go.id": {
  "mirror": "1",
  "site": "test-ipv6.polkam.go.id",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.polkam.go.id/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.polkam.go.id/images-nc/knob_green.png",
  "loc": "ID",
  "provider": "Coordinating Ministry For Political, Legal, and Security Affairs of Indonesia",
  "monitor": "vicky@polkam.go.id",
  "reason": ""
 },
 "test-ipv6.ro": {
  "mirror": "1",
  "site": "test-ipv6.ro",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.ro/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.ro/images-nc/knob_green.png",
  "loc": "RO",
  "provider": "RCS \u0026 RDS",
  "monitor": "Liviu Pislaru \u003cliviu.pislaru@rcs-rds.ro\u003e",
  "reason": ""
 },
 "test-ipv6.roedu.net": {
  "mirror": "1",
  "site": "test-ipv6.roedu.net",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.roedu.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.roedu.net/images-nc/knob_green.png",
  "loc": "RO",
  "provider": "RoEduNet",
  "monitor": "IPv6 @ RoEduNet \u003cipv6@roedu.net\u003e",
  "reason": ""
 },
 "test-ipv6.se": {
  "mirror": "1",
  "site": "test-ipv6.se",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.se/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.se/images-nc/knob_green.png",
  "loc": "SE",
  "provider": "Interlan Gefle AB",
  "monitor": "torbjorn.eklov@interlan.se \u003ctorbjorn.eklov@interlan.se\u003e",
  "reason": ""
 },
 "test-ipv6.showmyip.ca": {
  "mirror": "1",
  "site": "test-ipv6.showmyip.ca",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.showmyip.ca/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.showmyip.ca/images-nc/knob_green.png",
  "loc": "UK",
  "provider": "Christopher Munz-Michielin",
  "monitor": "Christopher Munz-Michielin \u003cchristopher@showmyip.ca\u003e",
  "reason": ""
 },
 "test-ipv6.si": {
  "mirror": "1",
  "site": "test-ipv6.si",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.si/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.si/images-nc/knob_green.png",
  "loc": "SI",
  "provider": "Damjan Sirnik",
  "monitor": "Damjan Sirnik \u003cdamjan@sirnik.si\u003e",
  "reason": ""
 },
 "test-ipv6.sjc.vr.org": {
  "mirror": "1",
  "site": "test-ipv6.sjc.vr.org",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.sjc.vr.org/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.sjc.vr.org/images-nc/knob_green.png",
  "loc": "US CA",
  "provider": "vr.org",
  "monitor": "jfesler@gigo.com",
  "reason": ""
 },
 "test-ipv6.tld.sk": {
  "mirror": "1",
  "site": "test-ipv6.tld.sk",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.tld.sk/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.tld.sk/images-nc/knob_green.png",
  "loc": "SK",
  "provider": "Sk-nic",
  "monitor": "SK-NIC, a.s. \u003chostmaster@sk-nic.sk\u003e",
  "reason": ""
 },
 "test-ipv6.tokyo.gigo.com": {
  "mirror": "1",
  "site": "test-ipv6.tokyo.gigo.com",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.tokyo.gigo.com/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.tokyo.gigo.com/images-nc/knob_green.png",
  "loc": "JP",
  "provider": "Jason Fesler (@linode Tokyo)",
  "monitor": "",
  "reason": ""
 },
 "test-ipv6.vtt.net": {
  "mirror": "1",
  "site": "test-ipv6.vtt.net",
  "hide": "0",
  "v4": "http://ipv4.test-ipv6.vtt.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.vtt.net/images-nc/knob_green.png",
  "loc": "RU",
  "provider": "JSC \"Volgatranstelecom\"",
  "monitor": "VTT Network Operations Centre \u003cnoc@vtt.net\u003e",
  "reason": ""
 },
 "testipv6.de": {
  "mirror": "1",
  "site": "testipv6.de",
  "hide": "0",
  "v4": "http://ipv4.testipv6.de/images-nc/knob_green.png",
  "v6": "http://ipv6.testipv6.de/images-nc/knob_green.png",
  "loc": "DE",
  "provider": "COSIMO Vertriebs -und Beratungs GmbH",
  "monitor": "COSIMO WebTeam \u003ckontakt@testipv6.de\u003e",
  "reason": ""
 },
 "www.ctbc.com.br": {
  "mirror": "0",
  "site": "www.ctbc.com.br",
  "hide": "0",
  "v4": "http://ipv4only.ctbc.net.br/ctbc/pixel.gif",
  "v6": "http://ipv6only.ctbc.net.br/ctbc/pixel.gif",
  "loc": "BR",
  "provider": "Algar Telecom / CTBC",
  "monitor": "",
  "reason": ""
 },
 "www.duiadns.net": {
  "mirror": "0",
  "site": "www.duiadns.net",
  "hide": "0",
  "v4": "http://ipv4.duiadns.net/1x1.gif",
  "v6": "http://ipv6.duiadns.net/1x1.gif",
  "loc": "NL",
  "provider": "Duiadns",
  "monitor": "Liviu Pislaru \u003cliviu.pislaru@duiadns.net\u003e",
  "reason": ""
 },
 "www.excathedra.co": {
  "mirror": "0",
  "site": "www.excathedra.co",
  "hide": "0",
  "v4": "https://ipv4.excathedra.co/knob_valid_green.png",
  "v6": "https://ipv6.excathedra.co/knob_valid_green.png",
  "loc": "UK",
  "provider": "Ex Cathedra Photography",
  "monitor": "Steve Durbin \u003csteved@excathedra.co\u003e",
  "reason": ""
 },
 "www.heise.de": {
  "mirror": "0",
  "site": "www.heise.de",
  "hide": "0",
  "v4": "http://www.four.heise.de/icons/ho/heise.gif",
  "v6": "http://www.six.heise.de/icons/ho/heise.gif",
  "loc": "DE",
  "provider": "Heise",
  "monitor": "Johannes Endres, c't \u003cje@heise.de\u003e",
  "reason": ""
 },
 "www.radioradicale.it": {
  "mirror": "0",
  "site": "www.radioradicale.it",
  "hide": "0",
  "v4": "http://ipv4.radioradicale.it/sites/www.radioradicale.it/files/pagine/2015/12/ipv6.png",
  "v6": "http://ipv6.radioradicale.it/sites/www.radioradicale.it/files/pagine/2015/12/ipv6.png",
  "loc": "IT",
  "provider": "Centro di Produzione Spa - AS57329",
  "monitor": "Dario Centofanti \u003cdario@popinga.net\u003e",
  "reason": ""
 },
 "www.rascom.ru": {
  "mirror": "0",
  "site": "www.rascom.ru",
  "hide": "0",
  "v4": "http://wood.rascom.ru/ipv4.jpg",
  "v6": "http://wood6.rascom.ru/logo2.png",
  "loc": "RU",
  "provider": "RASCOM",
  "monitor": "",
  "reason": ""
 },
 "www.rcs-rds.ro": {
  "mirror": "0",
  "site": "www.rcs-rds.ro",
  "hide": "0",
  "v4": "http://ipv4.rcs-rds.ro/1x1.gif",
  "v6": "http://ipv6.rcs-rds.ro/1x1.gif",
  "loc": "RO",
  "provider": "RCS \u0026 RDS",
  "monitor": "Liviu Pislaru \u003cliviu.pislaru@rcs-rds.ro\u003e",
  "reason": ""
 },
 "www.steffann.nl": {
  "mirror": "0",
  "site": "www.steffann.nl",
  "hide": "0",
  "v4": "http://v4-only.steffann.nl/v4-only.png",
  "v6": "http://v6-only.steffann.nl/v6-only.png",
  "loc": "NL",
  "provider": "SJM Steffann Consultancy",
  "monitor": "Sander Steffann \u003csander@steffann.nl\u003e",
  "reason": ""
 },
 "www.yahoo.com": {
  "mirror": "0",
  "site": "www.yahoo.com",
  "hide": "0",
  "v4": "http://v4test.yahoo.com/eng/test/eye-test.png",
  "v6": "http://v6test.yahoo.com/eng/test/eye-test.png",
  "loc": "global",
  "provider": "Yahoo!",
  "monitor": "",
  "reason": ""
 },
 "zeop.re": {
  "mirror": "0",
  "site": "zeop.re",
  "hide": "0",
  "v4": "http://test-ipv4.zeop.re/ipv4/ipv4.png",
  "v6": "http://test-ipv6.zeop.re/ipv6/ipv6.png",
  "loc": "RE",
  "provider": "ZEOP",
  "monitor": "PAYET Fabien \u003cfabienpayet@zeop.re\u003e",
  "reason": ""
 }
};