   <p> 

{{ Consider trying the "netalyzr".  This is another site that runs a
java applet (which can do more than my site can, in just javascript).
I would find feedback about how you useful this site was for you. }}
{{ From the netalyzr staff: }}
</p>
<blockquote>
     <p >
       <A target="_blank"
href="http://netalyzr.icsi.berkeley.edu/m=testv6">Netalyzr</A> is a free
network debugging and diagnostic service written by researchers at the
International Computer Science Institute in Berkeley.  This tool runs from
within your Java-enabled web browser.  It automatically detects many
conditions which might cause problems with IPv6 connectivity, including
creating a list of all IP addresses, discovering IPv6 addresses that don't
work, detecting IPv6 rogue gateways, and a host of other network problems.
     </p>
</blockquote>
