
<p>{{ <b>How this site works:</b>  This site tells your browser to try and load
several remote javascript files.  Each file is on a different server.  After
each one finishes, we look at which ones worked - and which ones failed. 
Depending on the pattern, we can guess at IPv4 and IPv6 compatibility, and
sometimes suggest possible fixes. }}</p>

<p>{{ Some browser plugins enforce policies that are compatible with the above behavior.
They block connections that (to them) look like they might be 3rd party advertising or tracking.
There is no good way to identify this plugins from inside javascript; nor
any good way to work around it. }}</p>
