<p>
{{
Windows Vista and Windows 7 are both IPv6 ready.
Mac OS X 10.5 and higher is fine.
FreeBSD and Linux, all recent versions, are also fine.
When your Internet service provider offers IPv6 to you, these OSs are good.
You may still need to replace your router (wireless or wired), if it is not aware of IPv6.  
You'll have to consult with your Internet service provider on when IPv6 will be offered.
}}
</p>

<p>
{{
Windows XP users: My advice is to plan on upgrading before using IPv6.
It is technically possible to use IPv6 with XP, to a minimal extent.
}}
</p>
