
<p>{{ Many OS and Hardware manufacturers are making updates to help improve the transition to IPv6.  Some known "gotchas" are being addressed by workarounds by these vendors. }}</p>
<p>{{ You can do your part to make sure you are running the latest: }}</p>
<ul>
  <li>{{ OS - Make sure you have the latest. }}</li>
    <ul>
      <li class="os_osx">{{ Mac users: Apple OS X 10.6.7 is recommended for improved IPv6 support. }}</li>
      <li class="os_osx">{{ Mac users on 10.4 or 10.5 may need to disable IPv6 if other troubleshooting steps fail. }}</li>
      <li class="os_windows">{{ Windows users: go to }} <a href="http://update.microsoft.com">http://update.microsoft.com</a>.</li>
      <li class="os_ios">{{ iPhone/iPad users: No specific version advised at this time. }}</li>
    </ul>
  <li>{{ Routers - Make sure you have the latest firmware installed.  Some vendors have updated the defaults, or put in health checks before enabling IPv6. }}</li>
    <ul>
      <li>{{ If you are using an Apple router or Time Capsule, load the Airport Utility to check that your router is up to date. }}</li>
    </ul>
  <li>{{ Browsers - Some browsers have made updates to detect "broken" users, and to temporarily disable IPv6. }}
    <ul>
        <li>{{ Firefox 4.x now only tries IPv6, when an IPv6 address is configured.  Firefox 3 users are encouraged to upgrade. }}</li>
        <li>{{ Chrome: If a wrench icon appears on the browser toolbar, click it. Select "Update Google Chrome" then Restart. }}</li>
        <li>{{ Opera: Make sure you use at least 11.10. }}</li>
    </ul></li>
  
</ul>



