
<p>
{{ <b>If you strongly believe you have IPv6, but we were unable to detect it:</b> it
means one of a couple of things.  Either your organization is blocking the
use of IPv6 to talk to the outside Internet through network policy; or perhaps what you see with
IPv6 on your host is not a global address.  
Any address starting with "::", "fc", "fd", or "fe" are unable to work with the public IPv6 Internet.
 }}</p>

