  <p>
[% " If you are savvy with technology, you can be an early adopter of IPv6, consider learning more about  " | i18n %]
<a href="#" onclick="return help_page('faq_6to4.html','6to4')">6to4</a> 
[% " providers (managed 6to4 tunnel services).   " | i18n %]

[% " The use of automatic tunnels is discouraged" | i18n %] 
<a href="#" onclick="return help_page('faq_6to4.html','6to4')">[% "[see more]" | i18n %]</a>.
</p>
