<!--START helpdesk.inc -->

<div id="helpdesk" style="display:block">

    <div id="helpdesk_content">

      [% PROCESS "main/progress_bar.inc" %]

      <p>{{Help desk information will follow once the test completes.}}</p>
    </div>

</div>

<p></p>
<p>
<span style="font-size: x-small">
More information about this page, including how to bookmark it:
<a href="/faq_helpdesk.html">faq_helpdesk.html</a>.</span>
</p>



<div id=replayurldiv  style="display:none">
<hr/>
<div>
<p>
{{If your Internet help desk asks you to mail the 'results url',  copy and paste the following URL.}}
{{Note that this will share your current numeric Internet Protocol address(es).}}
{{We do not recommend posting this link on public web sites such as forums.}}
</p>
<div id=replayurl>-</div>
<p>
{{On most computers, you can right-click the above URL, and select 'Copy'.}}
</p>
</div>
</div>





<!-- STOP helpdesk.inc -->
