<div id="tabnavcontainer">
<ul id="tabnavlist">

<li id="tabbutton_helpdesk_link"><a href="#" class="tabbutton_helpdesk"  onclick='return GIGO.tabnav("helpdesk")'>{{For the Help Desk}}</a></li>
<li><a href="#" class="tabbutton_main" id="tabcurrent" onclick='return GIGO.tabnav("main")'>{{Summary}}</a></li>
<li><a href="#" class="tabbutton_tests"  onclick='return GIGO.tabnav("tests")'>{{Tests Run}}</a></li>
<li style="display:none" id="tabbutton_mail_link"><a href="#" class="tabbutton_mail"  onclick='return GIGO.tabnav("mail")'>{{Share Results / Contact}}</a></li>

<li id="faqtablink" style="display:none" class="navright"><a href="#" class="tabbutton_faq"  onclick='return GIGO.tabnav("faq")'>{{FAQ for You}}</a></li>
<li id="popuptablink" style="display:none" class="navright"><a href="#" class="tabbutton_popup"  onclick='return GIGO.tabnav("popup")' id="href_popup">{{Help Popup}}</a></li>

<li style="display:none" id="debuglink"><a href="#" class="tabbutton_debug"  onclick='return GIGO.tabnav("debug")'>{{Debug}}</a></li>
<li style="display:none" id="siteslink"><a href="#" class="tabbutton_sites"  onclick='return GIGO.tabnav("sites")'>{{Other IPv6 Sites}}</a></li>



</ul>
</div>

