<!-- START tests.inc -->


<div>
  <p><b>{{How this test works:}}</b> {{Your browser will be instructed to reach a series of URLs. The combination of successes and failures tells a story about how ready you are for when publishers start offering their web sites on IPv6.}}</p>
  <p>{{Click to see}}
   <a href="#" class="tabbutton_xxx" onclick='return GIGO.tabnav_tests("tech")'>{{Technical Info}}</a>
  </p>
<hr/>
</div>


    <table cellpadding="3" border="0" summary="tests run, and pass/fail">
      <tr>
        <td nowrap="nowrap">{{Test with IPv4 DNS record}}</td>

        <td nowrap="nowrap">&nbsp;</td>

        <td nowrap="nowrap">
          <div id="sum_test_a">
            {{pending}}
          </div>
        </td>

      </tr>

      <tr>
        <td nowrap="nowrap">{{Test with IPv6 DNS record}}</td>

        <td nowrap="nowrap">&nbsp;</td>

        <td nowrap="nowrap">
          <div id="sum_test_aaaa">
            {{pending}}
          </div>
        </td>

      </tr>

      <tr>
        <td nowrap="nowrap">{{Test with Dual Stack DNS record}}</td>

        <td nowrap="nowrap">&nbsp;</td>

        <td nowrap="nowrap">
          <div id="sum_test_ds">
            {{pending}}
          </div>
        </td>

      </tr>

      <tr>
        <td nowrap="nowrap">{{Test for Dual Stack DNS and large packet}}</td>

        <td nowrap="nowrap">&nbsp;</td>

        <td nowrap="nowrap">
          <div id="sum_test_dsmtu">
            {{pending}}
          </div>
        </td>

      </tr>

      <tr id="nossl1">
        <td nowrap="nowrap">{{Test IPv4 without DNS}}</td>

        <td nowrap="nowrap">&nbsp;</td>

        <td nowrap="nowrap">
          <div id="sum_test_ipv4">
            {{pending}}
          </div>
        </td>

      </tr>

      <tr id="nossl2">
        <td nowrap="nowrap">{{Test IPv6 without DNS}}</td>

        <td nowrap="nowrap">&nbsp;</td>

        <td nowrap="nowrap">
          <div id="sum_test_ipv6">
            {{pending}}
          </div>
        </td>

      </tr>

      <tr>
        <td nowrap="nowrap">{{Test IPv6 large packet}}</td>

        <td nowrap="nowrap">&nbsp;</td>

        <td nowrap="nowrap">
          <div id="sum_test_v6mtu">
            {{pending}}
          </div>
        </td>

      </tr>


      <tr>
        <td nowrap="nowrap">{{Test if your ISP's DNS server uses IPv6}}</td>

        <td nowrap="nowrap">&nbsp;</td>

        <td nowrap="nowrap">
          <div id="sum_test_v6ns">
            {{pending}}
          </div>
        </td>

      </tr>


      <tr>
        <td nowrap="nowrap">{{Find IPv4 Service Provider}}</td>

        <td nowrap="nowrap">&nbsp;</td>

        <td nowrap="nowrap">
          <div id="sum_test_asn4">
            {{pending}}
          </div>
        </td>

      </tr>

      <tr>
        <td nowrap="nowrap">{{Find IPv6 Service Provider}}</td>

        <td nowrap="nowrap">&nbsp;</td>

        <td nowrap="nowrap">
          <div id="sum_test_asn6">
            {{pending}}
          </div>
        </td>

      </tr>






      <tr class="optional_buggydns1" style="display:none">
        <td nowrap="nowrap">{{Test for buggy DNS}}</td>

        <td nowrap="nowrap">&nbsp;</td>

        <td nowrap="nowrap">
          <div id="sum_test_buggydns1">
            {{pending}}
          </div>
        </td>
      </tr>

    </table>

<div><p>
  {{Click to see}}
  <a href="#" class="tabbutton_mail"  onclick='return GIGO.tabnav("mail")'>{{Share Results / Contact}}</a></p></div>


<!-- STOP tests.inc -->
