#tabnavlist
{
padding: 3px 0;
margin-left: 0;
border-bottom: 1px solid #778;
font: bold 12px Verdana, sans-serif;
}

#tabnavlist li
{
list-style: none;
margin: 0;
display: inline;
}

#tabnavlist li a
{
padding: 3px 0.5em;
margin-left: 3px;
border: 1px solid #778;
border-bottom: none;
background: #DDE;
text-decoration: none;
}

#tabnavlist li a:link { color: #448; }
#tabnavlist li a:visited { color: #667; }

#tabnavlist li a:hover
{
color: #000;
background: #AAE;
border-color: #227;
}

#tabnavlist li a#tabcurrent
{
background: white;
color: black;
border-bottom: 1px solid white;
}

#tabnavlist li a#contactme
{
background: #ff9900;
color: #000000;
border-bottom: 2px solid yellow;
}




.tabnavright 
{
 float: right;
}