<hr/>
<div id="about">
<p>  Copyright (C) 2010, 2024 Jason Fesler. {{ All rights reserved. }}  Version [% .GitInfo.Version %] ([% .GitInfo.Hash %])<br/>

 <a href="/mirrors.html">{{ Mirrors }}</a> |
<!-- <a href="mission.html">{{ Mission }}</a> | -->
 <a href="https://github.com/falling-sky/source/wiki">{{ Source }}</a> |
<a href="/attributions.html">{{ Attributions }}</a>

  |

<a href="locale.html" onclick="return help_page('locale.html','Locale')">
<img src="/images/icon_987_red.png" class="em1" border="0" />{{locale}}</a>
{{percenttranslated}}

<br/>
[% PROCESS "inc/disclaimer.inc" %]
</p>
</div>

[% PROCESS "inc/fixup_html.inc" %]
[% PROCESS "inc/fixup_html_minimal.inc" %]

</body>
</html>
