<div id="noscript">
  <p id="score0">{{ JavaScript Required }}</p>
  
  
  <p>{{ This site requires JavaScript, as well as the ability to pull in cross-site scripts, in order to perform the testing. }}</p>
  <p>{{ If this message does not go away, it means that JavaScript has been disabled, either by a plugin or extension in your browser, or by explicit browser setting. }}</p>

  <p id="score1">{{ Do you use NoScript? }}</p>
  <p>
   {{ If you use this Firefox add-on, you'll need to
  "Temporarily allow all this page".   You will need to do this <b>twice</b> for everything to work.
  Alternately, disable NoScript entirely until you are done with this site. }}</p>

  <p>{{ You can opt instead to view the <a href="simple_test.html">simple test</a>, which
  will give you a quick pass/fail for IPv4, IPv4+IPv6, and IPv6.  It will however offer
  little diagnostic information. }}</p>
</div>
