<h1>{{ What is a tunnel? }}</h1>

<p>
	{{ A tunnel is a technique often used to transport one protocol over another one.
	For example, it is used by ADSL to transport PPP over ATM (a common technique
	for several Internet residential subscribers).  }}
</p>

<p>	
	{{ In the realm of IPv6, tunnels are used to transport: }}
</p>
	<ul>
	<li>{{ IPv6 packets over IPv4 network: then IPv4-only Internet users can reach the IPv6 Internet; }}</li>
	<li>{{ IPv4 packets over IPv6 network: then IPv6-only Internet users can reach the IPv4 Internet. }}</li>
	</ul>

