#! /usr/bin/perl
my $name = shift @ARGV or die;
my $command = "uglifyjs -b >/dev/null 2>/dev/null";

open(BUFFER,"<$name") or die "failed to read $name";
binmode BUFFER, ":utf8";
my $buffer;
read BUFFER,$buffer,1000000;
close BUFFER;


$buffer =~ s#[/][*].*?[*][/]##g;
$buffer =~ s#\r\n#\n#g;
$buffer =~ s#\r#\n#g;


@try = $buffer =~ m#^((?:var )?\S+\s*=[^\n]+{.*?\n};)#msg;

print "|$command\n";
open(PIPE,"|$command");
binmode PIPE, ":utf8";
print PIPE $buffer;
close PIPE and warn "no errors on input";


foreach my $try (@try) {
  my ($l) = split(/\n/,$try);
  open(PIPE,"|$command");
  binmode PIPE, ":utf8";
  print PIPE "$try\n";
  close PIPE or warn "CHECK: $l\n";
}