GIGO.sites_parsed={
 "8n1.org": {
  "site": "8n1.org",
  "mirror": false,
  "hide": false,
  "v4": "http://ip4.8n1.org/test.gif",
  "v6": "http://ip6.8n1.org/test.gif",
  "loc": "NL",
  "provider": "8n1.org - a simple pastebin",
  "monitor": "Sander Smeenk \u003csander@bit.nl\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "aa.net.uk": {
  "site": "aa.net.uk",
  "mirror": false,
  "hide": false,
  "v4": "http://ip4.aa.net.uk/images/aaisp_logo.png",
  "v6": "http://ip6.aa.net.uk/images/aaisp_logo.png",
  "loc": "UK",
  "provider": "AAISP (UK IPv6 ISP)",
  "monitor": "support@aa.net.uk",
  "contact": "Adrian Kennard \u003ca@k.gg\u003e",
  "reason": "",
  "transparent": false
 },
 "bvconline.com.ar": {
  "site": "bvconline.com.ar",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.bvconline.com.ar/knob_green.png",
  "v6": "http://ipv6.test-ipv6.bvconline.com.ar/knob_green.png",
  "loc": "AR",
  "provider": "BVNET S.A",
  "monitor": "Ariel Cuesta \u003carielc@vianet.com.ar\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "campaya.co.uk": {
  "site": "campaya.co.uk",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4.campaya.co.uk/apple-touch-icon.png",
  "v6": "http://ipv6.campaya.co.uk/apple-touch-icon.png",
  "loc": "UK",
  "provider": "Campaya",
  "monitor": "Claus Pedersen \u003cclausp@campaya.com\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "duplimaster.com": {
  "site": "duplimaster.com",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4.duplimaster.com/public/images/logo-sombra.png",
  "v6": "http://ipv6.duplimaster.com/public/images/logo-sombra.png",
  "loc": "ES",
  "provider": "duplimaster.com",
  "monitor": "Jesus Vara \u003cjvara@e-impresion.es\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "eurobilltracker.com": {
  "site": "eurobilltracker.com",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.eurobilltracker.com/img/1x1.gif",
  "v6": "http://ipv6.test-ipv6.eurobilltracker.com/img/1x1.gif",
  "loc": "FI",
  "provider": "EuroBillTracker",
  "monitor": "Anssi Johansson \u003canssi@miuku.net\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "google.com": {
  "site": "google.com",
  "mirror": false,
  "hide": false,
  "v4": "http://test-ipv6-dot-com-v6exp3-v4.metric.gstatic.com/v6exp3/6.gif",
  "v6": "http://test-ipv6-dot-com-v6exp3-v6.metric.gstatic.com/v6exp3/6.gif",
  "loc": "global",
  "provider": "Google",
  "monitor": "",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "he.net": {
  "site": "he.net",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4.tunnelbroker.net/images/helogo.gif",
  "v6": "http://ipv6.tunnelbroker.net/images/helogo.gif",
  "loc": "US (CA)",
  "provider": "HE.net",
  "monitor": "Hurricane Electric \u003cnoc@he.net\u003e",
  "contact": "Mike Tindle \u003cmtindle@he.net\u003e",
  "reason": "",
  "transparent": false
 },
 "ipv6-test.ch": {
  "site": "ipv6-test.ch",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4.ipv6-test.ch/images-nc/knob_green.png",
  "v6": "http://ipv6.ipv6-test.ch/images-nc/knob_green.png",
  "loc": "UK",
  "provider": "BSC-Telecom",
  "monitor": "Ken Booth \u003cken@ipv6-test.ch\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "ipv6-test.pl": {
  "site": "ipv6-test.pl",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.ipv6-test.pl/images-nc/knob_green.png",
  "v6": "http://ipv6.ipv6-test.pl/images-nc/knob_green.png",
  "loc": "PL",
  "provider": "Net-Admin",
  "monitor": "noc@net-admin.pl",
  "contact": "Net-Admin \u003cipv6@goodhost.eu\u003e",
  "reason": "",
  "transparent": false
 },
 "ipv6ready.me": {
  "site": "test-ipv6.epic.network",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.ipv6ready.me/images-nc/knob_green.png",
  "v6": "http://ipv6.ipv6ready.me/images-nc/knob_green.png",
  "loc": "JP",
  "provider": "Kazuhide Takahashi",
  "monitor": "kazuhide.t@ipv6ready.me",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "jamieweb.net": {
  "site": "jamieweb.net",
  "mirror": false,
  "hide": false,
  "v4": "https://ipv4.jamieweb.net/ipv4-only.png",
  "v6": "https://ipv6.jamieweb.net/ipv6-only.png",
  "loc": "UK",
  "provider": "Jamie Scaife (JamieOnUbuntu)",
  "monitor": "JamieOnUbuntu . \u003cjamieonubuntu@gmail.com\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "nic.br": {
  "site": "nic.br",
  "mirror": false,
  "hide": false,
  "v4": "http://v4.ipv6.br/img/logo-ipv6.png",
  "v6": "http://v6.ipv6.br/img/logo-ipv6.png",
  "loc": "BR",
  "provider": "NIC.br",
  "monitor": "Antonio M. Moreiras \u003cmoreiras@nic.br\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "nsx.de": {
  "site": "nsx.de",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4.nsx.de/images/knob_valid_green.png",
  "v6": "http://ipv6.nsx.de/images/knob_valid_green.png",
  "loc": "DE",
  "provider": "Stephan Fiebrandt (personal)",
  "monitor": "Stephan Fiebrandt \u003cstephan@nsx.de\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "sixte.st": {
  "site": "sixte.st",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.sixte.st/images-nc/knob_green.png",
  "v6": "http://ipv6.sixte.st/images-nc/knob_green.png",
  "loc": "SG",
  "provider": "Delan Azabani",
  "monitor": "Delan Azabani \u003cdelan@azabani.com\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "snozzages.com": {
  "site": "snozzages.com",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4.v6test.snozzages.com/1x1.gif",
  "v6": "http://ipv6.v6test.snozzages.com/1x1.gif",
  "loc": "US (VA)",
  "provider": "Warren Kumari",
  "monitor": "Warren Kumari \u003cwarren@kumari.net\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "stdio.be": {
  "site": "stdio.be",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4.stdio.be/images/knob_valid_green.png",
  "v6": "http://ipv6.stdio.be/images/knob_valid_green.png",
  "loc": "DE",
  "provider": "Andrew Yourtchenko (personal)",
  "monitor": "Andrew Yourtchenko \u003cayourtch@gmail.com\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6-ct.comcast.net": {
  "site": "test-ipv6-ct.comcast.net",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6-ct.comcast.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6-ct.comcast.net/images-nc/knob_green.png",
  "loc": "US",
  "provider": "Comcast",
  "monitor": "Comcast IPv6 Team \u003ccomcast-ipv6@cable.comcast.com\u003e",
  "contact": "",
  "reason": "",
  "transparent": true
 },
 "test-ipv6-pa.comcast.net": {
  "site": "test-ipv6-pa.comcast.net",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6-pa.comcast.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6-pa.comcast.net/images-nc/knob_green.png",
  "loc": "US",
  "provider": "Comcast",
  "monitor": "Comcast IPv6 Team \u003ccomcast-ipv6@cable.comcast.com\u003e",
  "contact": "",
  "reason": "",
  "transparent": true
 },
 "test-ipv6.alpinedc.ch": {
  "site": "test-ipv6.alpinedc.ch",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.alpinedc.ch/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.alpinedc.ch/images-nc/knob_green.png",
  "loc": "CH",
  "provider": "AlpineDC",
  "monitor": "Sebastien Morier \u003csmorier@alpinedc.ch\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.ams.vr.org": {
  "site": "test-ipv6.ams.vr.org",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.ams.vr.org/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.ams.vr.org/images-nc/knob_green.png",
  "loc": "NL",
  "provider": "vr.org",
  "monitor": "jfesler@gigo.com",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.arauc.br": {
  "site": "test-ipv6.arauc.br",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.arauc.br/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.arauc.br/images-nc/knob_green.png",
  "loc": "BR",
  "provider": "PoP-PR/RNP",
  "monitor": "equipe@pop-pr.rnp.br",
  "contact": "PoP-PR/RNP \u003cadmnet@pop-pr.rnp.br\u003e",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.arbor.net": {
  "site": "test-ipv6.arbor.net",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.arbor.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.arbor.net/images-nc/knob_green.png",
  "loc": "US",
  "provider": "Arbor Networks",
  "monitor": "Bill Cerveny \u003cadmin@v6research.net\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.azstarnet.az": {
  "site": "test-ipv6.azstarnet.az",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.azstarnet.az/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.azstarnet.az/images-nc/knob_green.png",
  "loc": "AZ",
  "provider": "AZSTARNET LLC",
  "monitor": "Nadir M. Aliyev \u003cnadir@azstarnet.az\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.carnet.hr": {
  "site": "test-ipv6.carnet.hr",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.carnet.hr/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.carnet.hr/images-nc/knob_green.png",
  "loc": "HR",
  "provider": "Croatian Academic and Research Network",
  "monitor": "CARNet \u003csysadm@carnet.hr\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.cgates.lt": {
  "site": "test-ipv6.cgates.lt",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.cgates.lt/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.cgates.lt/images-nc/knob_green.png",
  "loc": "LT",
  "provider": "Cgates",
  "monitor": "Marius Sokas \u003cmarius.sokas@cgates.lt\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.cl": {
  "site": "test-ipv6.cl",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.cl/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.cl/images-nc/knob_green.png",
  "loc": "CL",
  "provider": "NIC Chile",
  "monitor": "NIC Chile \u003csoporte@nic.cl\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.cmd.net.br": {
  "site": "test-ipv6.cmd.net.br",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.cmd.net.br/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.cmd.net.br/images-nc/knob_green.png",
  "loc": "BR",
  "provider": "CMD Informatica",
  "monitor": "Cesar Scoassabia \u003csuporte@cmd.net.br\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.com": {
  "site": "test-ipv6.com",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.com/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.com/images-nc/knob_green.png",
  "loc": "Varies",
  "provider": "Several locations around the world",
  "monitor": "",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.com.au": {
  "site": "test-ipv6.com.au",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.com.au/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.com.au/images-nc/knob_green.png",
  "loc": "AU",
  "provider": "Futzle Industries",
  "monitor": "Deborah Pickett \u003cdebbiep@icemoonprison.com\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.csclub.uwaterloo.ca": {
  "site": "test-ipv6.csclub.uwaterloo.ca",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.csclub.uwaterloo.ca/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.csclub.uwaterloo.ca/images-nc/knob_green.png",
  "loc": "CA",
  "provider": "University of Waterloo Computer Science Club",
  "monitor": "systems-committee@csclub.uwaterloo.ca",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.cz": {
  "site": "test-ipv6.cz",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.cz/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.cz/images-nc/knob_green.png",
  "loc": "CZ",
  "provider": "nic.cz",
  "monitor": "NOC NIC \u003cnoc@nic.cz\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.epic.network": {
  "site": "test-ipv6.epic.network",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.epic.network/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.epic.network/images-nc/knob_green.png",
  "loc": "US",
  "provider": "epic.network",
  "monitor": "test-ipv6@qpg.us",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.ernet.in": {
  "site": "test-ipv6.ernet.in",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.ernet.in/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.ernet.in/images-nc/knob_green.png",
  "loc": "IN",
  "provider": "IPv6 Division of ERNET India",
  "monitor": "praveen.misra@eis.ernet.in",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.fratec.net": {
  "site": "test-ipv6.fratec.net",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.fratec.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.fratec.net/images-nc/knob_green.png",
  "loc": "CR",
  "provider": "Sistemas Fratec S.A.",
  "monitor": "Jorge Frater \u003cjfrater@fratec.com\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.go6.si": {
  "site": "test-ipv6.go6.si",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.go6.si/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.go6.si/images-nc/knob_green.png",
  "loc": "SI",
  "provider": "Go6 Lab - Slovenian IPv6 Iniciative",
  "monitor": "Jan Zorz \u003cjan@go6.si\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.hkg.vr.org": {
  "site": "test-ipv6.hkg.vr.org",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.hkg.vr.org/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.hkg.vr.org/images-nc/knob_green.png",
  "loc": "HK",
  "provider": "vr.org",
  "monitor": "jfesler@gigo.com",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.hu": {
  "site": "test-ipv6.hu",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.hu/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.hu/images-nc/knob_green.png",
  "loc": "HU",
  "provider": "Polaris-N Systems",
  "monitor": "Polaris-N Systems \u003cinfo@polaris-n.hu\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.jp": {
  "site": "test-ipv6.jp",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.jp/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.jp/images-nc/knob_green.png",
  "loc": "JP",
  "provider": "BIGLOBE, Inc/Fullroute Pte. Ltd",
  "monitor": "Shin Shirahata \u003cinquiry@test-ipv6.jp\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.ke.liquidtelecom.net": {
  "site": "test-ipv6.ke.liquidtelecom.net",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.ke.liquidtelecom.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.ke.liquidtelecom.net/images-nc/knob_green.png",
  "loc": "KE",
  "provider": "Liquid Telecom",
  "monitor": "ipv6@liquidtelecom.com",
  "contact": "Liquid Telecom \u003cipv6@liquidtelecom.com\u003e",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.lazypaddle.com": {
  "site": "test-ipv6.lazypaddle.com",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.lazypaddle.com/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.lazypaddle.com/images-nc/knob_green.png",
  "loc": "US WI",
  "provider": "Dale Hartung",
  "monitor": "Dale Hartung \u003cdale@dghartung.com\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.monash.edu": {
  "site": "test-ipv6.monash.edu",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.monash.edu/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.monash.edu/images-nc/knob_green.png",
  "loc": "AU",
  "provider": "Monash University",
  "monitor": "John Mann \u003cJohn.Mann@monash.edu\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.netiter.dk": {
  "site": "test-ipv6.netiter.dk",
  "mirror": false,
  "hide": false,
  "v4": "http://test-ipv6.com.i42.test-ipv6.easyv6.net/ipv6-test.png",
  "v6": "http://test-ipv6.com.i32.test-ipv6.easyv6.net/ipv6-test.png",
  "loc": "DE",
  "provider": "Netiter ApS",
  "monitor": "Netiter Aps \u003ckontakt@netiter.dk\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.nl": {
  "site": "test-ipv6.nl",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.nl/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.nl/images-nc/knob_green.png",
  "loc": "NL",
  "provider": "BIT BV",
  "monitor": "Teun Vink \u003cteun@bit.nl\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.no": {
  "site": "test-ipv6.no",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.no/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.no/images-nc/knob_green.png",
  "loc": "NO",
  "provider": "Availo AS",
  "monitor": "Brynjar Eide \u003ctest-ipv6@availo.no\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.noroutetohost.net": {
  "site": "test-ipv6.noroutetohost.net",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.noroutetohost.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.noroutetohost.net/images-nc/knob_green.png",
  "loc": "GB",
  "provider": "NoRouteToHost",
  "monitor": "test-ipv6@noroutetohost.net",
  "contact": "David Wilkinson \u003ctest-ipv6@noroutetohost.net\u003e",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.ro": {
  "site": "test-ipv6.ro",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.ro/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.ro/images-nc/knob_green.png",
  "loc": "RO",
  "provider": "RCS \u0026 RDS",
  "monitor": "Liviu Pislaru \u003cliviu.pislaru@rcs-rds.ro\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.se": {
  "site": "test-ipv6.se",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.se/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.se/images-nc/knob_green.png",
  "loc": "SE",
  "provider": "Interlan Gefle AB",
  "monitor": "torbjorn.eklov@interlan.se \u003ctorbjorn.eklov@interlan.se\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.si": {
  "site": "test-ipv6.si",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.si/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.si/images-nc/knob_green.png",
  "loc": "SI",
  "provider": "Damjan Sirnik",
  "monitor": "Damjan Sirnik \u003cdamjan@sirnik.si\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.sin.vr.org": {
  "site": "test-ipv6.sin.vr.org",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.sin.vr.org/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.sin.vr.org/images-nc/knob_green.png",
  "loc": "SG",
  "provider": "vr.org",
  "monitor": "jfesler@gigo.com",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.tld.sk": {
  "site": "test-ipv6.tld.sk",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.tld.sk/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.tld.sk/images-nc/knob_green.png",
  "loc": "SK",
  "provider": "Sk-nic",
  "monitor": "\"SK-NIC, a.s.\" \u003chostmaster@sk-nic.sk\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.tni-au.mil.id": {
  "site": "test-ipv6.tni-au.mil.id",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.tni-au.mil.id/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.tni-au.mil.id/images-nc/knob_green.png",
  "loc": "ID",
  "provider": "Indonesian Air Force",
  "monitor": "Vicky Ezra Imanuel \u003cvicky@tni-au.mil.id\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.vtt.net": {
  "site": "test-ipv6.vtt.net",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.vtt.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.vtt.net/images-nc/knob_green.png",
  "loc": "RU",
  "provider": "JSC \"Volgatranstelecom\"",
  "monitor": "VTT Network Operations Centre \u003cnoc@vtt.net\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.vyncke.org": {
  "site": "test-ipv6.vyncke.org",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.vyncke.org/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.vyncke.org/images-nc/knob_green.png",
  "loc": "FR",
  "provider": "Éric Vyncke",
  "monitor": "Eric Vyncke \u003ceric@vyncke.org\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "test-ipv6.zw.liquidtelecom.net": {
  "site": "test-ipv6.zw.liquidtelecom.net",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.test-ipv6.zw.liquidtelecom.net/images-nc/knob_green.png",
  "v6": "http://ipv6.test-ipv6.zw.liquidtelecom.net/images-nc/knob_green.png",
  "loc": "ZW",
  "provider": "Liquid Telecom",
  "monitor": "ipv6@liquidtelecom.com",
  "contact": "Liquid Telecom \u003cipv6@liquidtelecom.com\u003e",
  "reason": "",
  "transparent": false
 },
 "testipv6.de": {
  "site": "testipv6.de",
  "mirror": true,
  "hide": false,
  "v4": "http://ipv4.testipv6.de/images-nc/knob_green.png",
  "v6": "http://ipv6.testipv6.de/images-nc/knob_green.png",
  "loc": "DE",
  "provider": "COSIMO Vertriebs -und Beratungs GmbH",
  "monitor": "COSIMO WebTeam \u003ckontakt@testipv6.de\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "www.ctbc.com.br": {
  "site": "www.ctbc.com.br",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4only.ctbc.net.br/ctbc/pixel.gif",
  "v6": "http://ipv6only.ctbc.net.br/ctbc/pixel.gif",
  "loc": "BR",
  "provider": "Algar Telecom / CTBC",
  "monitor": "Tiago Carrijo Setti \u003ctiagoc@algartelecom.com.br\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "www.duiadns.net": {
  "site": "www.duiadns.net",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4.duiadns.net/1x1.gif",
  "v6": "http://ipv6.duiadns.net/1x1.gif",
  "loc": "NL",
  "provider": "Duiadns",
  "monitor": "Liviu Pislaru \u003cliviu.pislaru@duiadns.net\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "www.excathedra.co": {
  "site": "www.excathedra.co",
  "mirror": false,
  "hide": false,
  "v4": "https://ipv4.excathedra.co/knob_valid_green.png",
  "v6": "https://ipv6.excathedra.co/knob_valid_green.png",
  "loc": "UK",
  "provider": "Ex Cathedra Photography",
  "monitor": "Steve Durbin \u003csteved@excathedra.co\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "www.heise.de": {
  "site": "www.heise.de",
  "mirror": false,
  "hide": false,
  "v4": "http://www.four.heise.de/icons/ho/heise.gif",
  "v6": "http://www.six.heise.de/icons/ho/heise.gif",
  "loc": "DE",
  "provider": "Heise",
  "monitor": "Johannes Endres, c't \u003cje@heise.de\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "www.joram.it": {
  "site": "www.joram.it",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4.joram.it/oggetti/immagini/ipv4.png",
  "v6": "http://ipv6.joram.it/oggetti/immagini/ipv6.jpg",
  "loc": "IT",
  "provider": "Joram.IT",
  "monitor": "Servizio Partners - Joram.IT \u003ccontact@joram.it\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "www.nop.hu": {
  "site": "www.nop.hu",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4.nop.hu/hosted.png",
  "v6": "http://ipv6.nop.hu/hosted.png",
  "loc": "HU",
  "provider": "nop.hu",
  "monitor": "matecs \u003cmatecs@niif.hu\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "www.radioradicale.it": {
  "site": "www.radioradicale.it",
  "mirror": false,
  "hide": false,
  "v4": "http://ipv4.radioradicale.it/sites/www.radioradicale.it/files/pagine/2015/12/ipv6.png",
  "v6": "http://ipv6.radioradicale.it/sites/www.radioradicale.it/files/pagine/2015/12/ipv6.png",
  "loc": "IT",
  "provider": "Centro di Produzione Spa - AS57329",
  "monitor": "Dario Centofanti \u003cdario@popinga.net\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "www.rascom.ru": {
  "site": "www.rascom.ru",
  "mirror": false,
  "hide": false,
  "v4": "http://wood.rascom.ru/ipv4.jpg",
  "v6": "http://wood6.rascom.ru/logo2.png",
  "loc": "RU",
  "provider": "RASCOM",
  "monitor": "Андрей Сафонов \u003cas@rascom.ru\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "www.steffann.nl": {
  "site": "www.steffann.nl",
  "mirror": false,
  "hide": false,
  "v4": "http://v4-only.steffann.nl/v4-only.png",
  "v6": "http://v6-only.steffann.nl/v6-only.png",
  "loc": "NL",
  "provider": "SJM Steffann Consultancy",
  "monitor": "Sander Steffann \u003csander@steffann.nl\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "www.tecpeu.com.br": {
  "site": "www.tecpeu.com.br",
  "mirror": false,
  "hide": false,
  "v4": "http://www.ipv4.tecpeu.com.br/img/logo-big.png",
  "v6": "http://www.ipv6.tecpeu.com.br/img/logo-big.png",
  "loc": "BR",
  "provider": "Tecpeu Informática",
  "monitor": "Ricardo Peu Grassi \u003ccontato@tecpeu.com.br\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "www.vyncke.org/ipv6status/": {
  "site": "www.vyncke.org/ipv6status/",
  "mirror": false,
  "hide": false,
  "v4": "https://test4.vyncke.org/knob_valid_green.png",
  "v6": "https://test6.vyncke.org/knob_valid_green.png",
  "loc": "FR",
  "provider": "Eric Vyncke (personal)",
  "monitor": "Eric Vyncke \u003ceric@vyncke.org\u003e",
  "contact": "",
  "reason": "letsencrypt SSL certs don't support AAAA only",
  "transparent": false
 },
 "www.yahoo.com": {
  "site": "www.yahoo.com",
  "mirror": false,
  "hide": false,
  "v4": "http://v4test.yahoo.com/eng/test/eye-test.png",
  "v6": "http://v6test.yahoo.com/eng/test/eye-test.png",
  "loc": "global",
  "provider": "Yahoo!",
  "monitor": "ipv6@yahoo-inc.com",
  "contact": "",
  "reason": "",
  "transparent": false
 },
 "ziggoforum.nl": {
  "site": "ziggoforum.nl",
  "mirror": false,
  "hide": false,
  "v4": "https://ipv4.ziggoforum.nl/images/pixel.gif",
  "v6": "https://ipv6.ziggoforum.nl/images/pixel.gif",
  "loc": "NL",
  "provider": "Ziggo Gebruikersforum",
  "monitor": "Rene Kemp \u003crene.kemp@outlook.com\u003e",
  "contact": "",
  "reason": "",
  "transparent": false
 }
};